- name: Setup WebServer
  hosts: websrvgrp
  become: yes
  tasks:
          - name: Install Apache http
            yum:
                    name: httpd
                    state: present
          - name: Start & Enable HTTPD
            service:
                    name: httpd
                    state: started
                    enabled: yes
          - name: Copy file with owner and permissions
            copy:
                  src: index.html
                  dest: /var/www/html/index.html
                  owner: root
                  group: root
                  mode: '0644'
                  backup: yes

- name: Setup DBserver
  hosts: dbsrvgrp
  become: yes
  tasks:
          - name: Install MySQL server
            yum:
                    name: mariadb-server
                    state: present
          - name: Start & Enable mariadb service
            service:
                    name: mariadb
                    state: started
                    enabled: yes
